routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index')->name('home');

/*Route::resource('movies', 'MoviesController');*/

Route::get('/actors','ActorController@index');
Route::get('/oneActor/{actor}', 'ActorController@showActor')->name('one.actor');

Auth::routes();
Route::get('/home', 'HomeController@index')->name('home');

//CRUD routes
Route::resource('comments', 'CommentController');


Route::get('/movies','MoviesController@list')
    ->name('movie.List');

Route::get('/movieOne/{movie}','MoviesController@showById')
    ->name('movies.show');

Route::get('/movieSearch/{search}', 'MoviesController@search')
    ->name('movies.search');
Route::get('/genre','GenreController@index');
Route::get('/years','YearsController@index');

app/Genre.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Genre extends Model
{
    protected $table = "genre";
    protected $filliable  = [
        "id",
        ""
    ];
}

app/Models/Actor.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Actor extends Model
{
    protected $hidden=[
      'id'
    ];


}

app/Models/Comment.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Comment extends Model
{
    protected $fillable=[
        'title','content','user_id'
    ];

//    function getUserAttribute(){
//        return User::find($this->user_id);
//    }
}

app/Movie.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Movie extends Model
{
    protected $hidden=[
        'id'
    ];
}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Year.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Year extends Model
{
    //
}

app/Http/Controllers/ActorController.php
<?php

namespace App\Http\Controllers;

use App\Models\Actor;
use Illuminate\Http\Request;

class ActorController extends Controller
{
    function index()
    {
        return view('actors', [
            'actor' => Actor::all()
        ]);
    }

    function showActor(Actor $actor)
    {
        return view('oneActor', [
            'actor' => $actor
        ]);
    }

    function search(Actor $actor)
    {
        $act = DB::table('movies')->where('id', $actor->id)->first();
        return view('welcome',[
            'actorSearch' => $act
        ]);
    }
}//movies
//movieOne/1
//marvaldc.nn
//actors
//actorOne/1

app/Http/Controllers/CommentController.php
<?php

namespace App\Http\Controllers;

use App\Models\Comment;
use App\Movie;
use Illuminate\Http\Request;

class CommentController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth')->except(['index','show']);
    }
    public function index()
    {
        return view('comments.index' ,[
        'title' => 'Комментарии',
        'comments' => Comment::all()
        ]);
    }
    public function create(Movie $movie)
    {
        return view('comments.form',[
            'title' => 'Новый комментарий',
            'movie' => $movie
        ]);
    }
    protected function rules(){
        return[
          'title'=>'required',
          'content'=>'required'
        ];
    }
    public function store(Request $request, Movie $movie)
    {
        $request->validate($this->rules());


        $data = $request->except('_token');
        $comment=new Comment($data);
        $comment->movie_id = $movie;
        $comment->user_id=auth()->user()->id;
        $comment->save();

        return redirect()->route('movieOne', $comment->movie_id);
    }

    public function show(Comment $comment)
    {
        return view('movieOne',[
            'title' => $comment->title,
            'comment' => $comment
        ]);
    }

    public function edit(Comment $comment)
    {
        $this->authorize('update', $comment);
        return view('comments.form',[
           'title'=>'Изменить' . $comment->title,
           'comment' => $comment
        ]);
    }

    public function update(Request $request, Comment $comment)
    {
        $this->authorize('update', $comment);
        $request->validate($this->rules());
        $data=$request->except(['_token', '_method']);
        $comment->fill($data);
        $comment->save();
        return redirect()->route('movieOne', $comment);
    }

    public function destroy(Comment $comment)
    {
        $this->authorize('delete', $comment);
        $comment->delete();
        return redirect()->route('comments.index');
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/GenreController.php
<?php

namespace App\Http\Controllers;

use App\Genre;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class GenreController extends Controller
{
    function index()
    {
        return view('genre',[
            'genres' => Genre::all()
        ]);
    }


    function showById(Genre $genre)
    {
        $connectionGenre = DB::table('connectionId')->select()->where('genreId', '=', $genre->id)->first();
        $searchMovie = DB::table('movies')->where('id', '=', $connectionGenre->moviesId)->get();
        $searchYear = DB::table('years')->where('id', '=', $connectionGenre->yearId)->get();
        return view('genre', [
            'moviesByGenre' => $searchMovie,
            'yearsByGenre' => $searchYear
        ]);
    }


    function search(Genre $genre)
    {
        $zhanr = DB::table('genre')->where('genreName', '=', $genre->genreName)->first();
        return view('welcome',[
            'movieSearch' => $zhanr
        ]);
    }
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use App\Movie;
use Illuminate\Http\Request;

class HomeController extends Controller
{
//   public function __construct()
//   {
//       $this->middleware('auth');
//   }

    function index()
    {
        return view('welcome',[
            'movies' => Movie::all()
        ]);
    }
}

app/Http/Controllers/MoviesController.php
<?php

namespace App\Http\Controllers;

use App\Models\Comment;
use App\Movie;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class MoviesController extends Controller
{
    function list()
    {
        return view('movie',[
            'movies' => Movie::all()
        ]);
    }

    function showById(Movie $movie)
    {
        $comments = Comment::all();
        $connectionMovie = DB::table('connectionid')->select()->where('moviesId', '=', $movie->id)->first();
        $searchGenre = DB::table('genre')->where('id', '=', $connectionMovie->genreId)->get();
        $searchActors = DB::table('actors')->where('id', '=', $connectionMovie->actorsId)->get();
        $searchYear = DB::table('years')->where('id', '=', $connectionMovie->yearId)->get();
        return view('movieOne', [
            'movieOne' => $movie,
            'yearsByMovie' => $searchYear,
            'genresByMovie' => $searchGenre,
            'actorsByMovie' => $searchActors,
            'comments' => $comments
        ]);
    }

    function search($search)
    {
        $film = Movie::findOrFail($search);
        return view('movieSearch', [
            'movieSearch' => $film
        ]);
    }

}

app/Http/Controllers/YearsController.php
<?php

namespace App\Http\Controllers;

use App\Year;
use Illuminate\Http\Request;

class YearsController extends Controller
{
    function index()
    {
        return view('year',[
            'years' => Year::all()
        ]);
    }
}

resources/views/404.blade.php
<!DOCTYPE html>
<html lang="en" class="no-js">

<!-- 40414:39-->
<head>
	<!-- Basic need -->
	<title>Open Pediatrics</title>
	<meta charset="UTF-8">
	<meta name="description" content="">
	<meta name="keywords" content="">
	<meta name="author" content="">
	<link rel="profile" href="#">

    <!--Google Font-->
    <link rel="stylesheet" href='http://fonts.googleapis.com/css?family=Dosis:400,700,500|Nunito:300,400,600' />
	<!-- Mobile specific meta -->
	<meta name=viewport content="width=device-width, initial-scale=1">
	<meta name="format-detection" content="telephone-no">

	<!-- CSS files -->
	<link rel="stylesheet" href="../../public/css/plugins.css">
	<link rel="stylesheet" href="../../public/css/style.css">

</head>
<body>
<!--preloading-->
<div id="preloader">
    <img class="logo" src="../../public/images/logo1.png" alt="" width="119" height="58">
    <div id="status">
        <span></span>
        <span></span>
    </div>
</div>
<!--end of preloading-->
<!--login form popup-->
<div class="login-wrapper" id="login-content">
    <div class="login-content">
        <a href="#" class="close">x</a>
        <h3>Login</h3>
        <form method="post" action="#">
        	<div class="row">
        		 <label for="username">
                    Username:
                    <input type="text" name="username" id="username" placeholder="Hugh Jackman" pattern="^[a-zA-Z][a-zA-Z0-9-_\.]{8,20}$" required="required" />
                </label>
        	</div>

            <div class="row">
            	<label for="password">
                    Password:
                    <input type="password" name="password" id="password" placeholder="******" pattern="(?=^.{8,}$)((?=.*\d)|(?=.*\W+))(?![.\n])(?=.*[A-Z])(?=.*[a-z]).*$" required="required" />
                </label>
            </div>
            <div class="row">
            	<div class="remember">
					<div>
						<input type="checkbox" name="remember" value="Remember me"><span>Remember me</span>
					</div>
            		<a href="#">Forget password ?</a>
            	</div>
            </div>
           <div class="row">
           	 <button type="submit">Login</button>
           </div>
        </form>
        <div class="row">
        	<p>Or via social</p>
            <div class="social-btn-2">
            	<a class="fb" href="#"><i class="ion-social-facebook"></i>Facebook</a>
            	<a class="tw" href="#"><i class="ion-social-twitter"></i>twitter</a>
            </div>
        </div>
    </div>
</div>
<!--end of login form popup-->
<!--signup form popup-->
<div class="login-wrapper"  id="signup-content">
    <div class="login-content">
        <a href="#" class="close">x</a>
        <h3>sign up</h3>
        <form method="post" action="#">
            <div class="row">
                 <label for="username-2">
                    Username:
                    <input type="text" name="username" id="username-2" placeholder="Hugh Jackman" pattern="^[a-zA-Z][a-zA-Z0-9-_\.]{8,20}$" required="required" />
                </label>
            </div>

            <div class="row">
                <label for="email-2">
                    your email:
                    <input type="password" name="email" id="email-2" placeholder="" pattern="(?=^.{8,}$)((?=.*\d)|(?=.*\W+))(?![.\n])(?=.*[A-Z])(?=.*[a-z]).*$" required="required" />
                </label>
            </div>
             <div class="row">
                <label for="password-2">
                    Password:
                    <input type="password" name="password" id="password-2" placeholder="" pattern="(?=^.{8,}$)((?=.*\d)|(?=.*\W+))(?![.\n])(?=.*[A-Z])(?=.*[a-z]).*$" required="required" />
                </label>
            </div>
             <div class="row">
                <label for="repassword-2">
                    re-type Password:
                    <input type="password" name="password" id="repassword-2" placeholder="" pattern="(?=^.{8,}$)((?=.*\d)|(?=.*\W+))(?![.\n])(?=.*[A-Z])(?=.*[a-z]).*$" required="required" />
                </label>
            </div>
           <div class="row">
             <button type="submit">sign up</button>
           </div>
        </form>
    </div>
</div>
<!--end of signup form popup-->

<div class="page-single-2">
	<div class="container">
		<div class="row">
			<div class="middle-content">
				<a href="welcome.blade.php"><img class="md-logo" src="images/logo1.png" alt=""></a>
				<img src="images/uploads/err-img.png" alt="">
				<h1>Page not found</h1>
				<a href="welcome.blade.php" class="redbtn">go home</a>
			</div>
		</div>
	</div>
</div>
<script src="js/jquery.js"></script>
<script src="js/plugins.js"></script>
<script src="js/plugins2.js"></script>
<script src="js/custom.js"></script>
</body>

<!-- 40414:54-->
</html>

resources/views/_partials/navbar.blade.php
<nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
    <div class="container">
        <a class="navbar-brand" href="{{ url('/') }}">
            {{ config('app.name', 'MarvelDC') }}
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <!-- Left Side Of Navbar -->
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a href="{{route('comments.index')}}" class="nav-lnk">Комментарии</a>
                </li>
            </ul>

            <!-- Right Side Of Navbar -->
            <ul class="navbar-nav ml-auto">
                <!-- Authentication Links -->
                @guest
                    <li class="nav-item">
                        <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                    </li>
                    @if (Route::has('register'))
                        <li class="nav-item">
                            <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                        </li>
                    @endif
                @else
                    <li class="nav-item dropdown">
                        <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                            {{ Auth::user()->name }}<span class="caret"></span>
                        </a>

                        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="{{ route('logout') }}"
                               onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                {{ __('Logout') }}
                            </a>

                            <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                @csrf
                            </form>
                        </div>
                    </li>
                @endguest
            </ul>
        </div>
    </div>
</nav>

resources/views/actors.blade.php
@extends('layouts.main')


@section('content')
    <br>
    <br>
<div class="page-single">
    <div class="container">
        <div class="row ipad-width2">
            <div class="col-md-9 col-sm-12 col-xs-12">
                <div class="row">
                    <div class="col-md-4">
                        @foreach($actor as $act)
                        <div class="ceb-item-style-2">
                            <img src={{url($act->url)}} alt="">
                            <div class="ceb-infor">
                                <h2><a href="{{route('one.actor', $act->id)}}">{{$act->FIO}}</a></h2>
                                <span>actor, uk</span>
                            </div>
                        </div>
                        @endforeach
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<form id="filter-sidebar" action="{{route('one.actor', $act->id)}}" method="get">
    <div class="filter-select-wrap">
        <input id="filter-address" class="filter-select filter-tax" name="location" data-address='{{$act->FIO}}' type="text" placeholder="Actor location"/>
        <ul class="ul-addresses"></ul>
    </div>
</form>
    <br>
    <br>
    <br>
    <br>

<script>
    //функция поиска совпадений вводимых символов
    function findEl(el, array, value) {
        var coincidence = false;
        el.empty();//очищаем список совпадений
        for (var i = 0; i < array.length; i++){
            if (array[i].match('^'+value)){//проверяем каждый елемент на совпадение побуквенно
                el.children('li').each(function (){//проверяем есть ли совпавшие елементы среди выведенных
                    if(array[i] === $(this).text()) {
                        coincidence = true;//если есть совпадения то true
                    }
                });
                if(coincidence === false){
                    el.append('<li class="js-filter-address">'+array[i]+'</li>');//если нету совпадений то добавляем уникальное название в список
                }
            }
        }
    }

    var filterInput = $('#filter-address'),
        filterUl = $('.ul-addresses');
    //проверка при каждом вводе символа
    filterInput.bind('input propertychange', function(){
        if($(this).val() !== ''){
            filterUl.fadeIn(100);
            findEl(filterUl,$(this).data('address'),$(this).val());
        }
        else{
            filterUl.fadeOut(100);
        }
    });
    //при клике на елемент выпадалки присваиваем значение в инпут и ставим триггер на его изменение
    filterUl.on('click','.js-filter-address', function(e){
        $('#filter-address').val('');
        filterInput.val($(this).text());
        filterInput.trigger('change');
        filterUl.fadeOut(100);
    });
</script>
@endsection

resources/views/comments/form.blade.php
<?php
$update=isset($comment);
?>
@extends('layouts.main')

@section('content')
    <br>
    <br>
    <br>
    <br>
<h1>{{$title}}</h1>
    <form action="{{route('comments.store', $movie->id)}}" method="POST" class="card card-body">
        @csrf
        @if($update)
            @method('PUT')
            @endif
           <div class="form-group">
               <label for="title">Название<span class="text-danger">*</span></label>
               <input type="text"
                      name="title"
                      id="title"
                      class="form-control @error('title') is-invalid @enderror"
                      placeholder="Введите заголовок..."
                      value="{{old('title') ?? ($comment->title ?? '')}}">
               @error('title')
               <div class="invalid-feedback">
                   {{$message}}
               </div>
               @enderror
           </div>

            <div class="form-group">
                <label for="content">Комментарий<span class="text-danger">*</span></label>
                <textarea name="content"
                          id="content"
                          class="form-control @error('content') is-invalid @enderror"
                          placeholder="Напишите отзыв о фильме">{{old('content') ?? ($comment->content ?? '')}}</textarea>
                @error('content')
                <div class="invalid-feedback">
                    {{$message}}
                </div>
                @enderror
            </div>
        <div>
        <button class="btn-success">{{$update ? 'Обновить комментарии' : 'Написать комментарии'}}</button>
        </div>
    </form>
    <br>
    <br>
    <br>
    <br>
@endsection

resources/views/comments/index.blade.php
@extends('layouts.main')

@section('content')
<br>
<br>
<br>
<br>
    <div class="d-flex align-content-between align-items-center">
        <h1>Комментарии</h1>
        @if(Auth::check())
        <a href="{{route('comments.create')}}" class="btn btn-success ml-auto">
            Написать коментарии
        </a>
        @endif
    </div>
    @forelse($comments as $comment)
        <a href="{{route('comments.show', $comment)}}" class="mb-3 card card-body">
            <h3 class="mb-0">
            {{$comment->content}}
            </h3>
        </a>
        @empty
        <div class="alert alert-secondary">Комментариев пока что нету</div>
    @endforelse

    <br>
    <br>
    <br>
    <br>
    <br>
@endsection

resources/views/comments/show.blade.php
@extends('layouts.main')

@section('content')
    <br>
    <br>
    <br>
    <br>
    <br>
    @if(auth()->check())
        <div class="mb-3 btn-group btn-group-sm">
            @if(auth()->user()->can('update',$comment))
            <a class="btn btn-info" href="{{route('comments.edit', $comment)}}">Изменить</a>
                @endif
                @if(auth()->user()->can('delete',$comment))
                    <a class="btn btn-danger delete-link" href="{{route('comments.destroy', $comment)}}" data-target="delete-form">Удалить</a>
                    <form id="delete-form" action="{{route('comments.destroy', $comment)}}" method="POST" class="d-none">
                        @csrf
                        @method('DELETE')
                    </form>
                @endif
        </div>
        @endif


    <h1>{{$comment->title}}</h1>
    <p class="lead">{{$comment->content}}</p>


@if(auth()->user()->can('delete', $comment))
    <script>
        let link=document.querySelector('.delete-link');
        let id=link.dataset.target;
        link.addEventListener('click', function (event) {
            event.preventDefault();
            document.getElementById(id).submit();
        });
    </script>
    @endif

    <br>
    <br>
    <br>
    <br>
    @endsection

resources/views/genre.blade.php
@extends('layouts.main')


@section('content')
    <br>
    <br>
    <div class="page-single">
        <div class="container">
            <div class="row ipad-width2">
                <div class="col-md-9 col-sm-12 col-xs-12">
                    <div class="row">
                        <div class="col-md-4">
                            @foreach($genres as $gen)
                                <div class="ceb-item-style-2">
                                    <h2>{{$gen->genreName}}</h2>
                                </div>
                            @endforeach
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
    </div>
@endsection

resources/views/movie.blade.php
@extends('layouts.main')

@section('content')
<br>
<br>
<br>
<div class="page-single">
    <div class="container">
        <div class="row ipad-width2">
            <div class="col-md-9 col-sm-12 col-xs-12">
                    <div class="row">
                        @foreach($movies as $movie)
                        <div class="col-md-4">
                            <div class="ceb-item-style-2">
                                <div class="movie-item">
                                    <div class="mv-img">
                                        <img src={{url($movie->url)}} alt="" width="285" height="437">
                                    </div>
                                    <div class="title-in">
                                        <h6><a href="{{route('movies.show', $movie->id)}}">{{$movie->FilmName}}</a></h6>
                                    </div>
                                </div>
                            </div>
                        </div>
                        @endforeach
                    </div>
            </div>
        </div>
    </div>
</div>

@endsection

resources/views/movieOne.blade.php
@extends('layouts.main')

@section('content')
    <br>
    <br>
    <br>
    <br>
    <div class="row ipad-width2">
        <div class="col-md-4 col-sm-12 col-xs-12">
            <div class="movie-img sticky-sb">
                <img src={{url($movieOne->url)}} alt="">

            </div>
        </div>
        <div class="col-md-8 col-sm-12 col-xs-12">
            <div class="movie-single-ct main-content">
                <h1 class="bd-hd">{{$movieOne->FilmName}}<span>2015</span></h1>
                <div class="movie-tabs">
                    <div class="tabs">
                        <ul class="tab-links tabs-mv">
                            <li class="active"><a href="#overview">Overview</a></li>
                            <li><a href="#reviews"> Reviews</a></li>
                        </ul>
                        <div class="tab-content">
                            <div id="overview" class="tab active">
                                <div class="row">
                                    <div class="col-md-8 col-sm-12 col-xs-12">
                                        <!-- movie cast -->
                                        <div class="mvcast-item">
                                            <div class="cast-it">
                                                @foreach($actorsByMovie as $actors)
                                                    <div class="cast-left">
                                                        <div class="col-md-3">
                                                            <div class="row-cols-md-12">
                                                                <img src={{url($actors->url)}} alt="">
                                                            </div>
                                                        </div>
                                                        <a href="#">{{$actors->FIO}}</a>
                                                    </div>
                                                @endforeach
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-4 col-xs-12 col-sm-12">
                                        <div class="sb-it">
                                            <h6>Stars: </h6>
                                            @foreach($actorsByMovie as $actors)
                                                <p><a href="#">{{$actors->FIO}}</a>
                                            @endforeach
                                        </div>
                                        <div class="sb-it">
                                            <h6>Genres:</h6>
                                            @foreach($genresByMovie as $genres)
                                                <p><a href="#">{{$genres->genreName}}</a>
                                            @endforeach
                                        </div>
                                        <div class="sb-it">
                                            <h6>Release Date:</h6>
                                            @foreach($yearsByMovie as $years)
                                                <p>{{$years->dateFilm}}</p>
                                            @endforeach
                                        </div>
                                        <div class="ads">
                                            <img src="images/uploads/ads1.png" alt="">
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div id="reviews" class="tab review">
                                <div class="row">
                                    <div class="rv-hd">
                                        <div class="div">
                                            <h2>{{$movieOne->FilmName}}</h2>
                                        </div>
                                        @if(Auth::check())
                                            <a href="{{route('comments.create', $movieOne->id)}}" class="redbtn">Write Comment</a>
                                        @endif
                                    </div>
                                    @forelse($comments as $comment)
                                        <a href="{{route('comments.show', $comment)}}" class="mb-3 card card-body">
                                            <h3 class="mb-0">
                                                {{$comment ?? ''}}
                                            </h3>
                                        </a>
                                    @empty
                                        <div class="alert alert-secondary">Комментариев пока что нету</div>
                                    @endforelse

                                    @if(auth()->check())
                                        <div class="mb-3 btn-group btn-group-sm">
                                            @if(auth()->user()->can('update',$comment ?? ''))
                                                <a class="btn btn-info" href="{{route('comments.edit', $comment ?? '')}}">Изменить</a>
                                            @endif
                                            @if(auth()->user()->can('delete',$comment ?? ''))
                                                <a class="btn btn-danger delete-link" href="{{route('comments.destroy', $comment ?? '')}}" data-target="delete-form">Удалить</a>
                                                <form id="delete-form" action="{{route('comments.destroy', $comment ?? '')}}" method="POST" class="d-none">
                                                    @csrf
                                                    @method('DELETE')
                                                </form>
                                            @endif
                                        </div>
                                    @endif
                                    <h1>{{$comment ?? ''}}</h1>
                                    <p class="lead">{{$comment ?? ''}}</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
<!--    @if(auth()->user()->can('delete', $comment ?? ''))
        <script>
            let link=document.querySelector('.delete-link');
            let id=link.dataset.target;
            link.addEventListener('click', function (event) {
                event.preventDefault();
                document.getElementById(id).submit();
            });
        </script>
    @endif
    -->
    <br>
    <br>
    <br>
    <br>
@endsection